# Generated by Django 4.0.6 on 2022-12-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourtube', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YTchannel',
            new_name='YoutubeChannel',
        ),
    ]
