# Generated by Django 4.0.6 on 2022-12-21 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ourtube', '0003_feed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='cahnnel_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='name',
            field=models.CharField(default='initial name', max_length=128),
            preserve_default=False,
        ),
    ]
