# Generated by Django 4.0.6 on 2022-12-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourtube', '0005_youtubechannel_playlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='channels',
            field=models.ManyToManyField(null=True, to='ourtube.youtubechannel'),
        ),
    ]
