# Generated by Django 4.0.6 on 2022-12-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourtube', '0006_alter_feed_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='channels',
            field=models.ManyToManyField(blank=True, to='ourtube.youtubechannel'),
        ),
    ]
