# Generated by Django 4.0.6 on 2022-12-27 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourtube', '0007_alter_feed_channels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubechannel',
            old_name='cahnnel_id',
            new_name='channel_id',
        ),
    ]
