# Generated by Django 4.1.4 on 2023-01-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourtube', '0008_rename_cahnnel_id_youtubechannel_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
