# Generated by Django 4.1.4 on 2023-01-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourtube', '0009_alter_feed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubechannel',
            name='channel_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='youtubechannel',
            name='playlist_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(models.F('user'), models.F('feed'), name='unique_members'),
        ),
    ]
